### ISSUE TITLE
Idealized single column test case

### ISSUE THREAD

**Issue by glwagner** [CliMA/ClimaOceanBiogeochemistry.jl#16]
We need to build out our `examples/` so that we can test new BGC models as we build them.

First we'd like to focus on an idealized, yet still reasonably complicated case (to reveal the non-trivial aspects of BGC dynamics).
One idea is to drive a single column model with data from the Hawaiian Ocean Timeseries: https://hahana.soest.hawaii.edu/hot/

Some todo:

- [ ] Download the data and plot it
- [ ] Figure out how to initialize the model from the HOT data and impose fluxes at the top of the model ?
- [ ] Relax the single column model back to the HOT data?
- [ ] Add a BGC model on top

Close this PR when the example is running in the documentation!
```[tasklist]
### Tasks
- [ ] Download the data and plot it
- [ ] Figure out how to initialize the model from the HOT data and impose fluxes at the top of the model ?
- [ ] Relax the single column model back to the HOT data?
- [ ] Add a BGC model on top
```
